spring.application.name=chat-backend

spring.data.mongodb.uri=${SPRING_MONGODB_CONNECTION_STRING:mongodb+srv://rutulprajapati2006_db_user:oBQGxfUtPKYo7lcR@cluster0.zgdvme4.mongodb.net/chatdb?appName=Cluster0}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:chatdb}

jwt.secret=${JWT_SECRET:chatAppSuperSecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLongEnough2024}
jwt.expiration=86400000

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=465
spring.mail.username=${BREVO_SMTP_LOGIN:af4fd8001@smtp-brevo.com}
spring.mail.password=${BREVO_SMTP_PASSWORD:xsmtpsib-d9479018f77230dd6616f3d3bb00d3dda67a9a11603f32b21143781851a00421-JxekAFj95Gxg6tJO}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

brevo.from.email=${BREVO_FROM_EMAIL:af4fd8001@smtp-brevo.com}
brevo.from.name=ChatApp

server.port=${PORT:8080}



