spring.application.name=chat-backend

spring.data.mongodb.uri=${SPRING_MONGODB_CONNECTION_STRING:mongodb+srv://rutulprajapati2006_db_user:oBQGxfUtPKYo7lcR@cluster0.zgdvme4.mongodb.net/chatdb?appName=Cluster0}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:chatdb}

jwt.secret=${JWT_SECRET:chatAppSuperSecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLongEnough2024}
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME:prajapatirutul952@gmail.com}
spring.mail.password=${GMAIL_APP_PASSWORD:zxhgogxrslkzqnvy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000

brevo.api.key=${BREVO_API_KEY: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}
brevo.from.email=prajapatirutul952@gmail.com
brevo.from.name=ChatApp

server.port=${PORT:8080}