spring.application.name=chat-backend

spring.mongodb.connection-string=${SPRING_MONGODB_CONNECTION_STRING:mongodb+srv://rutulprajapati2006_db_user:oBQGxfUtPKYo7lcR@cluster0.zgdvme4.mongodb.net/chatdb?appName=Cluster0}
spring.data.mongodb.uri=${SPRING_MONGODB_CONNECTION_STRING:mongodb+srv://rutulprajapati2006_db_user:oBQGxfUtPKYo7lcR@cluster0.zgdvme4.mongodb.net/chatdb?appName=Cluster0}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:chatdb}

jwt.secret=${JWT_SECRET:chatAppSecretKeyThatIsAtLeast256BitsLongForSecurity123456}
jwt.expiration=${JWT_EXPIRATION:86400000}

server.port=${PORT:8080}